apps/blog/urls.py
from django.urls import path
from .views import (
    blogOverview,
    articleView
)

urlpatterns = [
    path('', blogOverview, name="overview"),
    path('<slug:slug>/', articleView, name='article'),
]

apps/core/urls.py
from django.urls import path
from .views import (
    homePageView
)

urlpatterns = [
    path('', homePageView, name="hello"),
]

dj_editorjs/urls.py
from django.contrib import admin
from django.urls import (
    path, 
    include 
)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path('blog/', include(('apps.blog.urls', 'blog'), namespace='blog')),
    path('editorjs/', include('django_editorjs_fields.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.utils.text import slugify 
from django.conf import settings

from django_editorjs_fields import (
    EditorJsJSONField, 
    EditorJsTextField
)

# Create your models here.
class Article(models.Model):
    class Meta:
        ordering = ["-publish_date"]

    title = models.CharField(max_length=100, unique=True) #6 words
    subtitle = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)


    content = EditorJsJSONField(
        plugins=[
            "@editorjs/image",
            "@editorjs/header",
            "editorjs-github-gist-plugin",
            "@editorjs/code@2.6.0",  # version allowed :)
            "@editorjs/list@latest",
            "@editorjs/inline-code",
            '@editorjs/embed',
            '@editorjs/delimiter',
            '@editorjs/link',
            '@editorjs/marker',
            "@editorjs/table",
        ],
        tools={
            "Gist": {
                "class": "Gist"
            },

            "Image": {
                "config": {
                    "endpoints": {
                        "byFile": str(settings.MEDIA_ROOT),
                        "byUrl": str(settings.MEDIA_URL),
                    }
                }
            }
        },
        null = True,
        blank = True,
    )   #1,400 - 1,600 words
    meta_description = models.CharField(max_length=120, blank=True) # 120, 158, 168

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(blank=True, null=True)
    published = models.BooleanField(default=False)

    author = models.CharField(max_length=255, blank=True, null=True)
    #author = models.ForeignKey(Profile, on_delete=models.PROTECT)
    #tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, self.subtitle)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f'blogs/{self.slug}/'

apps/core/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

    def __str__(self):
        return self.username
# create user

apps/blog/views.py
import json
from django.shortcuts import (
    render,
    get_object_or_404
)
from .models import (
    Article,
)


def blogOverview(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'overview.html', context)


def articleView(request, slug):
    article = get_object_or_404(Article, slug=slug)
    content = json.dumps(article.content)
    context = {
        'article': article,
        'content': content
    }
    return render(request, 'article.html', context)

apps/core/views.py
from django.shortcuts import (
    render
)


def homePageView(request):
    context = {
    }
    return render(request, 'index.html', context)

apps/users/views.py
from django.shortcuts import render

# Create your views here.

apps/blog/templates/article.html
{% extends 'base.html' %}
{% load static %}

{% block head_imports %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock  %}

{% block title %}Blogs{% endblock %}

{% block content %}
    <main>
        <h1 class="article-header">{{ article.title }}</h1>
        <p class="article-about">
            By {{ article.author }} on {{ article.publish_date|date:"l, j F Y" }}
        </p>
        <hr class="divider">
        <div class="article-content" id="article-content">

        </div>
    </main>
{% endblock %}

{% block scripts %}
    <script>
        const articleContent = document.getElementById("article-content");
        let content = JSON.parse(JSON.stringify({{ content|safe }}));
        console.log(content);
        let blocks = content.blocks;
        console.log(blocks.length);
    
        for (let index = 0; index <= blocks.length; index++) {
            console.log(blocks[index], index);
    
            switch (blocks[index].type) {
                case "Header":
                    let head = document.createElement(`h${blocks[index].data.level}`);
                    head.textContent = blocks[index].data.text;
                    articleContent.appendChild(head);
                    break;
    
                case "Image":
                    let div = document.createElement("div");
                    let image = document.createElement("img");
                    let caption = document.createElement("small");
                    image.src = `${blocks[index].data.file.url}`;
                    image.style = "margin-top:10px;";
                    image.height = 200;
                    image.width = 200;
                    caption.textContent = blocks[index].data.caption;
                    caption.style = "margin-top:5px;";
                    div.appendChild(image);
                    div.appendChild(caption);
                    div.style = "width:30%;display:grid;place-items:center";
                    articleContent.appendChild(div);
                    break;
    
                case "List":
                    let list;
                    if (blocks[index].data.style == "unordered") {
                        list = document.createElement("ul");
                    } else {
                        list = document.createElement("ol");
                    }
                    for (const item in blocks[index].data.items) {
                        let li = document.createElement("li");
                        li.textContent = blocks[index].data.items[item];
                        list.appendChild(li);
                    }
                    articleContent.appendChild(list);
                    break;
    
                case "Raw":
                    let blockquote = document.createElement("blockquote");
                    let code = document.createElement("code");
                    let pre = document.createElement("pre");
                    pre.textContent = blocks[index].data.html;
                    pre.style.background = "#dddddd";
                    pre.style.color = "#131313";
                    pre.style.padding = "15px";
                    code.appendChild(pre);
                    articleContent.appendChild(code);
                    break;
    
                case "Attaches":
                    let parent = document.createElement("div");
                    parent.style =
                        "margin-top:10px;width:30%; padding:10px; border:1px solid black;border-radius:8px;";
                    let a = document.createElement("a");
                    let name = document.createElement("h4");
                    a.href = `${blocks[index].data.file.url}`;
                    a.textContent = `Download ${blocks[index].data.file.extension} (${
                        blocks[index].data.file.size / 1000
                    } kb)`;
                    a.style = "grid-column: 1 / span 2";
                    name.textContent = blocks[index].data.file.name;
    
                    parent.appendChild(name);
                    parent.appendChild(a);
    
                    articleContent.appendChild(parent);
                    break;
    
                case "paragraph":
                    const p = document.createElement("p");
                    p.innerHTML = blocks[index].data.text;
                    articleContent.appendChild(p);
                    break;
    
                case "Link":
                    let parent2 = document.createElement("div");
                    let a2 = document.createElement("a");
                    parent2.style =
                        " margin-top:10px; width:30%;display:grid; grid-template-columns: 1fr 50px; padding:10px; border:1px solid black;border-radius:8px;";
    
                    if (blocks[index].data.meta.title) {
                        let title = document.createElement("p");
                        title.textContent = blocks[index].data.meta.title;
                        parent2.appendChild(title);
                    }
                    if (blocks[index].data.meta.image.url !== "") {
                        let parent3 = document.createElement("div");
                        let img = document.createElement("img");
    
                        img.src = blocks[index].data.meta.image.url;
                        parent3.style = " display:grid;place-items:center";
    
                        img.height = 40;
                        img.width = 40;
                        parent3.appendChild(img);
                        parent2.appendChild(parent3);
                    }
    
                    if (blocks[index].data.meta.description) {
                        let desc = document.createElement("small");
                        desc.style = "grid-column: 1 / span 2";
                        desc.textContent = blocks[index].data.meta.description;
                        parent2.appendChild(desc);
                    }
                    a2.style = "text-decoration:none;color:black";
                    a2.href = blocks[index].data.link;
                    a2.appendChild(parent2);
                    articleContent.appendChild(a2);
                    break;
    
                default:
                    break;
            }
        }
    </script>
{% endblock %}

apps/blog/templates/overview.html
{% extends 'base.html' %}
{% load static %}

{% block head_imports %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock  %}

{% block title %}Blogs{% endblock %}

{% block content %}
    <main>
        <h1>Welcome to the blog</h1>
        <div class="articles">
            {% for article in articles %}
            <div  class="article" id="{{ article.title }}">
                <h2 class="article-header">
                    <img src="{{ article.image.url }}" class="prod-image" alt="{{ article.title }} {{ article.subtitle }}">
                    <a href="{% url 'blog:article' article.slug %}">
                        {{ article.title }}
                    </a>
                </h2>

                <p class="article-about">
                    By {{ article.author }} on {{ article.publish_date|date:"l, j F Y" }}
                </p>
                <hr class="divider">
                <p class="article-summary">
                    {{ article.meta_description }}
                </p>
            </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

apps/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {# Meta #}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {# Fonts #}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    {# Icon #}

    {# Imports #}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {# Page specific imports block #}
    {% block head_imports %}
    {% endblock %}
    

    {# Title for each page #}
    <title>{% block title %}{% endblock %} | Test</title>

</head>

<body class="body" id="body">
    
    {% block content %}
    {% endblock content %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

apps/core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}


{% block content %}
    <main>
        <h1>Welcome</h1>
        <div>
            <p>Proceed to </p>
            <a href="{% url 'blog:overview' %}" class="btn btn-primary">Blog</a>
        </div>
    </main>

{% endblock %}